# Este es mi primer programa (6 de Octubre de 2021)
nombre = input("¿Cuál es tu nombre?: ")
apellidos = input("Apellidos: ")
print(nombre, ' ', apellidos)
print("Fin de la aplicación.")
print("Cambio directo en GitHub.")
